grocery_app/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user , logout_user, login_required, current_user
from flask import Flask
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem
from grocery_app.forms import GroceryStoreForm, GroceryItemForm
from grocery_app.models import GroceryStore, GroceryItem, User 
from grocery_app.forms import GroceryStoreForm, GroceryItemForm, LoginForm, SignUpForm


from grocery_app import app, db, bcrypt



##########################################
#           Routes                       #
##########################################

# TODO: Create a GroceryStoreForm


# TODO: If form was submitted and was valid:
# - create a new GroceryStore object and save it to the database,
# - flash a success message, and
# - redirect the user to the store detail page.

# TODO: Send the form to the template and use it to render the form fields

# TODO: Create a GroceryItemForm

# TODO: If form was submitted and was valid:
# - create a new GroceryItem object and save it to the database,
# - flash a success message, and
# - redirect the user to the item detail page.

# TODO: Send the form to the template and use it to render the form fields

# TODO: Create a GroceryStoreForm and pass in `obj=store`

 # TODO: If form was submitted and was valid:
# - update the GroceryStore object and save it to the database,
# - flash a success message, and
# - redirect the user to the store detail page.

 # TODO: Send the form to the template and use it to render the form fields

 # TODO: Create a GroceryItemForm and pass in `obj=item`

 # TODO: If form was submitted and was valid:
# - update the GroceryItem object and save it to the database,
# - flash a success message, and
# - redirect the user to the item detail page.

# TODO: Send the form to the template and use it to render the form fields


auth = Blueprint("auth", __name__)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    print('Print SignUp')
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash('Account Created')
        print('created')
        return redirect(url_for('auth.login'))
        print(form.errors)
    return render_template('signup.html', form=form)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('main.homepage'))
        else:
            print(user)
            
    print(form.errors)
    return render_template('login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.homepage'))



main = Blueprint("main", __name__)



@main.route('/')
def homepage():
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template('home.html', all_stores=all_stores)


@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    form = GroceryStoreForm()

    if form.validate_on_submit():
        new_grocery_store = GroceryStore(
            title=form.title.data,
            address=form.address.data,
            created_by=current_user
        )
        db.session.add(new_grocery_store)
        db.session.commit()

        flash('Successfully Created.')
        return redirect(url_for('main.store_detail', store_id=new_grocery_store.id))
    return render_template('new_store.html', form=form)


@main.route('/new_item', methods=['GET', 'POST'])
@login_required
def new_item():
    form = GroceryItemForm()

    if form.validate_on_submit():
        new_store_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
            created_by=current_user
        )
        db.session.add(new_store_item)
        db.session.commit()

        flash('Item created successfully.')
        return redirect(url_for('main.item_detail', item_id=new_store_item.id))
    return render_template('new_item.html', form=form)


@main.route('/store/<store_id>', methods=['GET', 'POST'])
@login_required
def store_detail(store_id):
    store = GroceryStore.query.get(store_id)
    created_by_user = User.query.get(store.created_by_id)


    form = GroceryStoreForm(obj=store)
    if form.validate_on_submit():
        store.title = form.title.data
        store.address = form.address.data

        db.session.add(store)
        db.session.commit()

        flash('Updated successfully.')
        return redirect(url_for('main.store_detail', store_id=store.id))

    store = GroceryStore.query.get(store_id)
    return render_template('store_detail.html', store=store, created_by_user=created_by_user, form=form)


@main.route('/item/<item_id>', methods=['GET', 'POST'])
@login_required

def item_detail(item_id):
    item = GroceryItem.query.get(item_id)
    created_by_user = User.query.get(item.created_by_id)

    form = GroceryItemForm(obj=item)

    if form.validate_on_submit():
        item.name = form.name.data
        item.price = form.price.data
        item.category = form.category.data
        item.photo_url = form.photo_url.data
        item.store = form.store.data

        db.session.add(item)
        db.session.commit()

        flash('Item updated.')
        return redirect(url_for('main.item_detail', item_id=item.id))

    item = GroceryItem.query.get(item_id)
    return render_template('item_detail.html', item=item, created_by_user=created_by_user, form=form)

@main.route('/shopping_list', methods=['GET'])
@login_required
def shopping_list():
    user = User.query.get(current_user.id)
    return render_template('shopping_list.html', user=user)


@main.route('/add_to_shopping_list/<item_id>', methods=['POST'])
@login_required
def add_to_shopping_list(item_id):
    user = User.query.get(current_user.id)
    item = GroceryItem.query.get(item_id)
    created_by_user = User.query.get(item.created_by_id)

    user.shopping_list_items.append(item)
    db.session.add(user)
    db.session.commit()

    flash('Item added.')
    return redirect(url_for('main.item_detail', item_id=item.id))






    
       
      

grocery_app/templates/base.html
<!DOCTYPE html>

<html>

    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>

    <body>

            <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                {% if current_user.is_authenticated %}
  Hi {{ current_user.name }}!
{% endif %}
                </div>

                <div>
                {% if current_user.is_authenticated %}
                <a href="/new_store">New Store</a>
                <a href="/new_item">New Item</a>
                <a href="/shopping_list">Shopping List</a>
                <a href="/logout">Log Out</a>
                {% else %}
                    <a href="/signup">Sign Up</a>
                    <a href="/login">Log In</a>
                {% endif %}
                </div>

            </nav>
            {% if current_user.is_authenticated %}
<p>You are logged in as {{ current_user.username }}</p>
{% endif %}

            {% block content %}{% endblock %}

        </div>

    </body>
    
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>One Place, All Your Grocery Needs!</em></p>

<h2>Grocery Store Directory</h2>

{% for store in all_stores %}

<div 

    class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>

</div>

{% endfor %}

{% endblock %}

grocery_app/templates/item.html
{{ form.photo_url.label }}

{{ form.photo_url }}


{{ form.store.label }}

{{ form.store }}


{{ form.name.label }}

{{ form.name }}


{{ form.price.label }}

{{ form.price }}


{{ form.category.label }}

{{ form.category }}



{{ form.submit }}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}


<h1>{{ item.name }}</h1>


<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>

<h3>Created By: <span style="font-weight: 100;">{{ created_by_user.username }}</span></h3>

<form method="POST" action="{{ url_for('main.add_to_shopping_list', item_id=item.id) }}">

    <button>Place in my Shopping List</button>

</form>



<form method="POST" action="{{ url_for('main.item_detail', item_id=item.id) }}">
    
    {{ form.csrf_token }}

    <fieldset>

        <legend>Please enter your information:</legend>
        {{ form.name.label }}
        {{ form.name }}
        {% for error in form.name.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}
        
        {{ form.price.label }}
        {{ form.price }}
        {% for error in form.price.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}

        {{ form.category.label }}
        {{ form.category }}
        {% for error in form.category.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}

        {{ form.photo_url.label }}
        {{ form.photo_url }}
        {% for error in form.photo_url.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}

        {{ form.store.label }}
        {{ form.store }}
        {% for error in form.store.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}

        {{ form.submit }}

    </fieldset>
    
</form>

{% endblock %}

grocery_app/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Login</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}


<h3>New Item</h3>

<form method= "POST" action= "{{ url_for('main.new_item') }}" >

    {{ form.csrf_token }}

    <fieldset>
        <legend>Enter Item information:</legend>

        {% include 'item.html' %}



    </fieldset>
</form>




{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST">
    <fieldset>
        <legend>Enter Store Information</legend>

        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        {{ form.csrf_token() }}
        {{ form.title.label() }}
        {{ form.title() }}
        {{ form.address.label() }}
        {{ form.address() }}
        {{ form.submit() }}

    </fieldset>
    
</form>


{% endblock %}

grocery_app/templates/shopping_list.html
{% extends 'base.html' %}
{% block content %}


<h3>Thanks for shopping with us.<h3>

<h1>{{ current_user.username }}, these items are in your shopping cart!</h1>

<h2>Items</h2>

<div class="items">
    {% for item in current_user.shopping_list_items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>

    {% endfor %}
    
</div>

{% endblock %}

grocery_app/templates/signup.html
<!-- signup.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<!-- TODO: Fill in the sign up form here! -->
<form action='/signup' method="POST">
    {{ form.csrf_token }}

    <fieldset>
    
        {{ form.username.label }}
        {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}

    </fieldset>

</form>

{% endblock %} 

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>


<h3>Address: <span style="font-weight: 100;">{{ store.address }}</span></h3> 


<h2>Created By: <span style="font-weight: 100;">{{ created_by_user.username }}</span></h2>



<div class="items">
    {% for item in store.items %}

    <div class="item-details">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px" height="200px">
    </div>

    {% endfor %}

</div>


<form method="POST" action="{{ url_for('main.store_detail', store_id=store.id) }}">

    {{ form.csrf_token }}

    <fieldset>

        <legend>Enter Store Details:</legend>
        {{ form.title.label }}
        {{ form.title }}
        {% for error in form.title.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}

        {{ form.address.label }}
        {{ form.address }}
        {% for error in form.address.errors %}
        <li style="color: red">{{ error }}</li>
        {% endfor %}
        
        {{ form.submit }}

    </fieldset>

</form>

{% endblock %}